### ISSUE TITLE
Some dependencies are not fixed and now they are causing docker-compose build issue

### ISSUE THREAD

**Issue by Ivasan7** [jhu-ep-coursera/capstone_demoapp#22]
Docker build fails with:
nokgiri 1.10.5 not compatible with ruby 2.2
public_suffix (4.0.3) not compatible with ruby 2.2
bson 4.7 not compatible with ruby 2.2

I have fixed them for now by adding fix version in the gemfile
nokogiri 1.6
public_suffic 3.1.1
bson 4.5

Not sure if everything will go well in the dev process. I'll keep the issue updated. If you have any/better suggestion I am happy to hear.

**Comment by Ivasan7** [comment]
Now thinking about it all required minimum ruby 2.3 so updating that in the Dockerfile is also a possible solution.

**Comment by Ivasan7** [comment]
Pushed Pull-Request for the latter solution.

**Comment by ejavaguy** [comment]
Thanks. I am actively looking at the issue to determine the path forward. 
The current ruby 2.2 base works with the posted solution and the gems you mention are likely added by your solution. No problem -- you have control over your environment and what you push to heroku. You can either use gems that work with ruby 2.2 or build a local or new Docker image based on 2.3 (which your pull request showed) -- so I am not holding you up while I walk thru a few scenarios.

**Comment by ejavaguy** [comment]
Thanks. I spent the last few days going through the capstone_demoapp and capstone_docker repositories and believe I have the dependencies and images set to values that will work for Ruby 2.3.8. Rather than update devise -- I chose to lock it down to a version that was consistent with the original course repository.
There were a few other issues addressed. ui-cropper 1.0.4 packaging had a bug that was fixed by an update to 1.0.6 and a small HTML change. Google Maps must have made a change that caused Capybara to evaluate various visible markers as non-visible and the rspec tests for that was addressed as well.

rake/rspec worked fine several times in my development environment and "docker-compose up rake" worked as well.

thanks for reporting
