### ISSUE TITLE
New things on the map/subjects page

### ISSUE THREAD

**Issue by k-topolyan** [jhu-ep-coursera/capstone_demoapp#8]
I've added a couple of new Images and Things to [your example](https://glacial-earth-69618.herokuapp.com/), the images are showing fine, but things are not fully.

They both have markers on the map itself, but we don't have any information about new things in the tabs (sd-current-things, etc.).

**Comment by k-topolyan** [comment]
I thought for a bit, maybe the problem is in the security policies, but I have not checked thoroughly.

I have 2 am, so good night :)

**Comment by ejavaguy** [comment]
Orphan Images are listed on the Subjects page because they have a position.
Things are only listed when they have a primary Image
 (ThingImage.priority=0) assigned because without it, the Thing has no
position. Since the Subjects page was geared at geolocating subjects -- it
seemed appropriate to leave off anything that did not have a position.

**Comment by k-topolyan** [comment]
OK, I changed priority of image for the first thing (5->0). Now the thing is showing up.
![map-github](https://cloud.githubusercontent.com/assets/10576847/25481487/12005f9c-2b56-11e7-9e5c-13a063f112bb.png)

It was just a little awkward, because the Thing had an Image (yes, with default priority) and it was visible on the map, but not in the tabs. But I think that's fine.
